{"uuid": "384065ec-aea7-4d22-8197-51580d233627", "children": ["6bb42d8b-9ca9-4412-897f-040d689edc6b"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1673697636815, "stop": 1673697636815}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/keshavsharma/Desktop/way2automation/c_pytest_framework_allure_reporting/test_j_screenshot_only_on_faliure.py\", line 17, in log_on_failure\n    if item.rep_call.failed:\n"}, "start": 1673697636871, "stop": 1673697636872}], "start": 1673697636815, "stop": 1673697636873}