{"uuid": "d8e52f06-90d6-486a-901c-8d4429d45a29", "children": ["1392e0b2-9e64-4a01-9752-5cb0c96f71ba"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1673697638267, "stop": 1673697638267}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/keshavsharma/Desktop/way2automation/c_pytest_framework_allure_reporting/test_j_screenshot_only_on_faliure.py\", line 17, in log_on_failure\n    if item.rep_call.failed:\n"}, "start": 1673697640449, "stop": 1673697640449}], "start": 1673697638267, "stop": 1673697640450}