{"uuid": "9cb3daaf-6128-4d9f-870f-ead74b091441", "children": ["a70630d4-c061-40a2-95b8-d0081e6e1b8b"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1673697636750, "stop": 1673697636751}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/keshavsharma/Desktop/way2automation/c_pytest_framework_allure_reporting/test_j_screenshot_only_on_faliure.py\", line 17, in log_on_failure\n    if item.rep_call.failed:\n"}, "start": 1673697639668, "stop": 1673697639669}], "start": 1673697636750, "stop": 1673697639669}